import json, os

questions = [
  # NARUTO
  ["What is the nine-tailed fox sealed inside Naruto?","Kurama","Shukaku","Gyuki","Matatabi","Naruto",200],
  ["What village is Naruto from?","Konohagakure","Sunagakure","Kirigakure","Kumogakure","Naruto",200],
  ["Who is Naruto's father?","Minato Namikaze","Jiraiya","Kakashi","Obito","Naruto",250],
  ["What is Naruto's signature jutsu?","Shadow Clone Jutsu","Rasengan","Chidori","Amaterasu","Naruto",200],
  ["What clan does Sasuke belong to?","Uchiha","Hyuga","Uzumaki","Senju","Naruto",200],
  ["Who are the three legendary Sannin of Konoha?","Jiraiya, Tsunade, Orochimaru","Kakashi, Minato, Guy","Itachi, Kisame, Pain","Hiruzen, Danzo, Homura","Naruto",300],
  ["Who teaches Naruto the Rasengan?","Jiraiya","Kakashi","Minato","Tsunade","Naruto",250],
  ["Who kills Itachi Uchiha in battle?","Sasuke","Naruto","Kakashi","Obito","Naruto",300],
  ["What dojutsu can copy any technique it sees?","Sharingan","Byakugan","Rinnegan","Tenseigan","Naruto",200],
  ["What village does Gaara lead as Kazekage?","Sunagakure","Kirigakure","Kumogakure","Iwagakure","Naruto",250],
  ["What is the forbidden jutsu that resurrects the dead?","Edo Tensei","Izanagi","Izanami","Kotoamatsukami","Naruto",400],
  ["What clan is Hinata from?","Hyuga","Uchiha","Uzumaki","Aburame","Naruto",250],
  ["Who is the true mastermind behind the Akatsuki?","Madara Uchiha","Obito Uchiha","Danzo","Orochimaru","Naruto",400],
  ["What is the name of Naruto's son in Boruto?","Boruto","Kawaki","Shinki","Inojin","Naruto",200],
  ["What is Shikamaru's clan technique?","Shadow Possession","Mind Transmission","Bug Swarm","Bone Release","Naruto",300],
  ["What is the name of the final villain in Naruto Shippuden?","Kaguya Otsutsuki","Madara Uchiha","Obito","Zetsu","Naruto",400],
  ["What is Lee's fighting style since he cannot use ninjutsu?","Taijutsu only","Genjutsu","Bukijutsu","Medical ninjutsu","Naruto",300],
  ["What space-time jutsu is Minato famous for?","Flying Raijin","Izanagi","Kamui","Hiraishin","Naruto",400],
  ["What tailed beast is sealed inside Gaara?","Shukaku (One-Tail)","Kurama (Nine-Tail)","Gyuki (Eight-Tails)","Matatabi (Two-Tails)","Naruto",350],
  ["What is the Akatsuki's goal?","Collect all tailed beasts","Destroy Konoha","Kill all kages","Revive the Sage of Six Paths","Naruto",300],
  # ONE PIECE
  ["What is the name of Luffy's pirate crew?","Straw Hat Pirates","Red Hair Pirates","Whitebeard Pirates","Heart Pirates","One Piece",200],
  ["What Devil Fruit did Luffy eat?","Gum-Gum Fruit","Flame-Flame Fruit","Chop-Chop Fruit","Smoke-Smoke Fruit","One Piece",200],
  ["What is the name of Zoro's three-sword style?","Santoryu","Nitoryu","Ittoryu","Kyutoryu","One Piece",300],
  ["Who is the cook of the Straw Hat Pirates?","Sanji","Zoro","Usopp","Franky","One Piece",200],
  ["What is Nami's role on the Straw Hat crew?","Navigator","Doctor","Sniper","Engineer","One Piece",200],
  ["What is the fleet admiral at Marineford?","Sengoku","Akainu","Aokiji","Kizaru","One Piece",350],
  ["What is Whitebeard's real name?","Edward Newgate","Marshall D. Teach","Donquixote Doflamingo","Silvers Rayleigh","One Piece",350],
  ["What is Haki?","Spiritual energy that can overpower Devil Fruits","A type of Devil Fruit","A sword technique","A Marine rank","One Piece",300],
  ["Who is Luffy's grandfather?","Monkey D. Garp","Monkey D. Dragon","Sengoku","Whitebeard","One Piece",300],
  ["What fruit does Ace eat?","Mera Mera no Mi (Fire-Fire Fruit)","Goro Goro no Mi","Magu Magu no Mi","Yami Yami no Mi","One Piece",350],
  ["What is Robin's Devil Fruit power?","Hana Hana no Mi - sprout body parts anywhere","Yomi Yomi no Mi","Ope Ope no Mi","Noro Noro no Mi","One Piece",300],
  ["What is Sanji's family name?","Vinsmoke","Donquixote","Charlotte","Gol","One Piece",400],
  ["Which Yonko does Luffy defeat in Wano?","Kaido","Big Mom","Shanks","Blackbeard","One Piece",350],
  ["What is Law's Devil Fruit ability?","Ope Ope no Mi - create operating rooms","Bara Bara no Mi","Gura Gura no Mi","Ito Ito no Mi","One Piece",400],
  ["What is the final island on the Grand Line?","Laugh Tale","Fishman Island","Marineford","Wano","One Piece",400],
  ["What is Roronoa Zoro's ambition?","To become the greatest swordsman in the world","To become a Marine admiral","To find All Blue","To help Luffy become King","One Piece",300],
  ["What is Nico Robin's true ability?","She can read Poneglyphs that record the true history of the world","She can fly","She has Future Sight Haki","She can grow body parts anywhere","One Piece",400],
  ["What is Brook's Devil Fruit?","Yomi Yomi no Mi - allowed him to return from the dead","Bane Bane no Mi","Suke Suke no Mi","Moru Moru no Mi","One Piece",350],
  ["What is Luffy's Gear 5 in One Piece?","His true Devil Fruit awakening as the Sun God Nika with rubber cartoon powers","An upgraded Gear 4","A transformation beyond Gear 4","A mythical Zoan form","One Piece",500],
  ["What is the true identity of Luffy's Devil Fruit?","Hito Hito no Mi Model Nika - Mythical Zoan of the Sun God","Gomu Gomu no Mi as always","Hito Hito no Mi Model Monkey","A special paramecia","One Piece",500],
  ["What is Conqueror Haki in One Piece?","The rarest Haki that can knock out weak-willed people","A type of Observation Haki","Advanced Armament Haki","A special technique of Yonko only","One Piece",400],
  ["What is Blackbeard's dual ability in One Piece?","Yami Yami no Mi (darkness) and Gura Gura no Mi (quake)","Yami Yami no Mi only","Gura Gura no Mi only","Two logia types","One Piece",450],
  # DRAGON BALL
  ["What is Goku's Saiyan birth name?","Kakarot","Raditz","Vegeta","Bardock","Dragon Ball",250],
  ["What are the seven orbs that summon Shenron?","Dragon Balls","Power Balls","Magic Orbs","Wish Spheres","Dragon Ball",200],
  ["What technique allows two people to fuse in Dragon Ball?","Fusion Dance","Potara earrings","Namekian fusion","Spirit Bomb","Dragon Ball",300],
  ["Who is the angel attendant of Universe 7's God of Destruction?","Whis","Vados","Martinu","Korn","Dragon Ball",350],
  ["What tournament do fighters from all 12 universes compete in Dragon Ball Super?","Tournament of Power","World Martial Arts Tournament","Cell Games","Tenkaichi Budokai","Dragon Ball",350],
  ["Who is Beerus the God of Destruction of?","Universe 7","Universe 6","Universe 11","Universe 1","Dragon Ball",300],
  ["What is Cell's ultimate form after absorbing both Androids?","Perfect Cell","Semi-Perfect Cell","Imperfect Cell","Ultra Cell","Dragon Ball",300],
  ["What is the name of Goku's son with Chichi?","Gohan","Goten","Gotenks","Bardock","Dragon Ball",200],
  ["What planet do Saiyans originally come from?","Planet Vegeta","Namek","Earth","Frieza's planet","Dragon Ball",300],
  ["What is Ultra Instinct's key feature?","Body moves without conscious thought","Maximum power","Time stop","Immortality","Dragon Ball",400],
  ["What is Frieza's final canon form?","Golden Frieza","White Frieza","Black Frieza","Ultimate Frieza","Dragon Ball",400],
  ["What is the Dragon Ball Fusion between Goku and Vegeta via Potara?","Vegito","Gogeta","Super Vegeta-Goku","Goketa","Dragon Ball",350],
  ["What is the Fusion Dance result between Goku and Vegeta?","Gogeta","Vegito","Super Fusion","Kakarot-Vegeta","Dragon Ball",350],
  ["What is the Hyperbolic Time Chamber in Dragon Ball?","One year inside equals one day outside","A place where time stops","A gravity training room","A spirit world","Dragon Ball",350],
  ["Who is Android 18's husband?","Krillin","Yamcha","Tien","Gohan","Dragon Ball",250],
  ["What is Vegeta's ultimate sacrifice in Dragon Ball Z?","Final Explosion attempting to destroy Majin Buu","Sacrificing himself for Gohan","Using his last energy for Goku","Merging with the Earth","Dragon Ball",400],
  ["What is the Hyperbolic Time Chamber's location?","Inside Kami's Lookout / Dende's Lookout","Inside Frieza's ship","On King Kai's planet","In the Afterlife","Dragon Ball",400],
  ["What is Kaio-ken technique in Dragon Ball?","A multiplier that increases power speed and senses at cost to the body","A time skip technique","A power-up using life force","A fusion with a Kai","Dragon Ball",350],
  ["What is Beerus's Hakai technique?","Destruction energy that erases existence from reality","A barrier technique","A pressure point attack","A ki concentration attack","Dragon Ball",400],
  ["Who is Goten in Dragon Ball?","Goku's second son who is the same age as Trunks","Gohan's brother who was born before the Cell Games","Goku's student","A child prodigy from another planet","Dragon Ball",300],
  # ATTACK ON TITAN
  ["What is the military branch that operates outside the walls in AoT?","Survey Corps","Military Police","Garrison Regiment","Titan Corps","Attack on Titan",200],
  ["Who is the Colossal Titan at the start of AoT?","Bertholdt Hoover","Reiner Braun","Annie Leonhart","Zeke Yeager","Attack on Titan",350],
  ["What are the vertical maneuvering devices called in AoT?","ODM Gear","3D Gear","Titan Gear","Survey Gear","Attack on Titan",250],
  ["What is Levi's last name in AoT?","Ackerman","Yeager","Kirstein","Blouse","Attack on Titan",250],
  ["Who is the Female Titan in AoT?","Annie Leonhart","Ymir","Historia","Sasha","Attack on Titan",300],
  ["What plan does Eren carry out at the end of AoT?","The Rumbling","The Founding","The Titan Shift","Wall Maria assault","Attack on Titan",400],
  ["Who kills Sasha Blouse in AoT?","Gabi Braun","Floch","Bertholdt","Porco","Attack on Titan",350],
  ["What is Zeke Yeager's titan power?","Beast Titan","Armored Titan","Warhammer Titan","Cart Titan","Attack on Titan",350],
  ["What nation do Warriors like Reiner come from?","Marley","Paradis","Hizuru","Mid-East Alliance","Attack on Titan",350],
  ["What is Eren Yeager's founding ability?","He can control all Titans and see memories of the future","He can only control his Attack Titan","He can create Titans from humans","He has all nine titan powers","Attack on Titan",400],
  ["Who is Historia Reiss in AoT?","The true queen of the walls with royal blood","A Survey Corps soldier","An Ackerman with titan power","A Marleyan spy","Attack on Titan",400],
  ["What is the Ackerman clan's ability in AoT?","They can tap into the power of all Ackermans before them giving superhuman strength","They are immune to Titan control","They have royal blood","They are Titan shifters","Attack on Titan",450],
  # MY HERO ACADEMIA
  ["What is Izuku Midoriya's hero name?","Deku","Shoto","Bakugo","Endeavor","My Hero Academia",200],
  ["What is the Quirk passed from hero to hero in MHA?","One For All","All For One","Full Cowling","Muscle Augmentation","My Hero Academia",200],
  ["Who is the Symbol of Peace in MHA?","All Might","Endeavor","Hawks","Mirko","My Hero Academia",200],
  ["What is Bakugo's Quirk?","Explosion","Ice and Fire","Engine","Frog","My Hero Academia",200],
  ["What school do the main MHA characters attend?","U.A. High School","Shiketsu","Ketsubutsu","Seiai","My Hero Academia",200],
  ["What is Shoto Todoroki's Quirk?","Half-Cold Half-Hot","Fire Release","Ice Age","Hellflame","My Hero Academia",200],
  ["Who is Deku's childhood friend and rival?","Katsuki Bakugo","Shoto Todoroki","Tenya Iida","Ochaco Uraraka","My Hero Academia",200],
  ["What is the name of Midoriya's homeroom teacher?","Shota Aizawa (Eraser Head)","All Might","Midnight","Present Mic","My Hero Academia",250],
  ["What Quirk can erase other Quirks in MHA?","Erasure","One For All","Decay","Nigh","My Hero Academia",300],
  ["Who is Tomura Shigaraki's mentor?","All For One","Stain","Kurogiri","Overhaul","My Hero Academia",300],
  ["What is Ochaco Uraraka's Quirk?","Zero Gravity","Frog","Engine","Creation","My Hero Academia",250],
  ["What is Todoroki's father's hero name?","Endeavor","Hellflame","Flame Hero","Fire Force","My Hero Academia",300],
  ["What are the Big Three at U.A.?","Mirio, Tamaki, and Nejire","Deku, Bakugo, Todoroki","All Might, Midnight, Present Mic","Hawks, Mirko, Best Jeanist","My Hero Academia",400],
  ["What is Eri's Quirk in MHA?","Rewind - reverting a person's body to a previous state","Time travel","Healing","Age control","My Hero Academia",400],
  # DEATH NOTE
  ["What is the notebook that kills people in Death Note?","Death Note","Book of Death","Shinigami Diary","Death Scroll","Death Note",200],
  ["What is the detective alias used by L in Death Note?","L","Kira","Ryuzaki","N","Death Note",200],
  ["What shinigami drops the Death Note in the human world?","Ryuk","Rem","Armonia Justin","Sidoh","Death Note",250],
  ["What must be written in the Death Note to kill?","The person's name while picturing their face","Their age","Their address","Their blood type","Death Note",200],
  ["What is the name of L's successor in Death Note?","Near (N)","Mello","Matt","Wammy","Death Note",350],
  ["What was L's real name in Death Note?","L Lawliet","Beyond Birthday","Nate River","Mihael Keehl","Death Note",400],
  ["How does Light die at the end of Death Note?","Shot by Matsuda then killed by Ryuk","L kills him","Near shoots him","He has a heart attack","Death Note",400],
  ["What food is L always eating in Death Note?","Sweets and cake","Ramen","Sushi","Pizza","Death Note",300],
  ["What is the shinigami Rem's role in Death Note?","She gave Misa a second Death Note and died saving her","She is Ryuk's partner","She helped Light win","She is the Death Note's creator","Death Note",400],
  ["What is Light Yagami's alias as Kira?","Kira (meaning killer in Japanese slang)","Justice","God","The Avenger","Death Note",300],
  # FMA BROTHERHOOD
  ["What is the first rule of alchemy in FMA?","Equivalent Exchange","Full Metal Law","Transmutation Circle","Human Sacrifice","FMAB",200],
  ["What did the Elric brothers attempt to bring back?","Their mother","Their father","Their dog","Their house","FMAB",200],
  ["What does Edward lose in the failed human transmutation?","His right arm and left leg","His eyes","His memory","His alchemy","FMAB",250],
  ["What is Al's body bound to after the failed transmutation?","A suit of armor","A doll","A statue","A shield","FMAB",200],
  ["Who is the main antagonist of FMA Brotherhood?","Father","Pride","Hohenheim","Gold-Toothed Doctor","FMAB",300],
  ["What is the Homunculus who is Fuhrer Bradley?","Wrath","Pride","Envy","Greed","FMAB",350],
  ["What is the Philosopher's Stone made from?","Human souls","Alchemy energy","Dragon blood","Transmuted gold","FMAB",350],
  ["Who is Edward's automail mechanic?","Winry Rockbell","Paninya","Gracia","Pinako","FMAB",300],
  ["What country are the Elric brothers from?","Amestris","Xing","Drachma","Creta","FMAB",300],
  ["What does Roy Mustang's alchemy control?","Fire (oxygen in air)","Water","Earth","Metal","FMAB",300],
  ["Who is Scar in FMA Brotherhood?","An Ishvalan survivor who kills State Alchemists","A Homunculus","A State Alchemist","A foreign spy","FMAB",350],
  ["What is the secret Father wants to become in FMA?","A god / transcend humanity","Immortal","A Philosopher's Stone","The Gate","FMAB",400],
  # DEMON SLAYER
  ["What is the name of Tanjiro's sister who was turned into a demon?","Nezuko","Kanao","Aoi","Shinobu","Demon Slayer",200],
  ["What organization hunts demons in Demon Slayer?","Demon Slayer Corps","Hashira Order","Wisteria Guild","Oni Hunters","Demon Slayer",200],
  ["What is the Flame Hashira who dies on the Mugen Train?","Kyojuro Rengoku","Sanemi Shinazugawa","Gyomei Himejima","Giyu Tomioka","Demon Slayer",250],
  ["What is Zenitsu's Breathing Style?","Thunder Breathing","Lightning Breath","Storm Breathing","Spark Breathing","Demon Slayer",250],
  ["What are the twelve elite demons under Muzan called?","Twelve Kizuki (Twelve Demon Moons)","Upper Ranks","Demon Lords","Oni Twelve","Demon Slayer",300],
  ["What is Inosuke's Breathing Style?","Beast Breathing","Wind Breathing","Stone Breathing","Mist Breathing","Demon Slayer",300],
  ["Who is the Love Hashira in Demon Slayer?","Mitsuri Kanroji","Kanao Tsuyuri","Shinobu Kocho","Aoi Kanzaki","Demon Slayer",300],
  ["What demon is the most powerful villain in Demon Slayer?","Muzan Kibutsuji","Kokushibo","Doma","Akaza","Demon Slayer",250],
  ["What is Tanjiro's main Breathing Style?","Water Breathing (later Sun Breathing)","Flame Breathing","Wind Breathing","Thunder Breathing","Demon Slayer",250],
  ["Who is the Water Hashira in Demon Slayer?","Giyu Tomioka","Tengen Uzui","Kyojuro Rengoku","Mitsuri Kanroji","Demon Slayer",250],
  ["What is the Sound Hashira's name in Demon Slayer?","Tengen Uzui","Giyu Tomioka","Rengoku Kyojuro","Kocho Shinobu","Demon Slayer",300],
  ["What is the Insect Hashira's name in Demon Slayer?","Kocho Shinobu","Kanao Tsuyuri","Aoi Kanzaki","Tamayo","Demon Slayer",300],
  ["What is the Mist Hashira's name in Demon Slayer?","Muichiro Tokito","Sanemi Shinazugawa","Gyomei Himejima","Mitsuri Kanroji","Demon Slayer",350],
  ["What is the Wind Hashira's name in Demon Slayer?","Sanemi Shinazugawa","Tomioka Giyu","Tokito Muichiro","Uzui Tengen","Demon Slayer",350],
  ["What is the Sun Breathing technique Tanjiro masters?","Hinokami Kagura","Dance of Fire","Solar Flame Dance","Flame God's Dance","Demon Slayer",350],
  ["Who is Kokushibo in Demon Slayer?","Upper Rank One - a former Demon Slayer and Yoriichi's twin","He is Muzan's first demon","He created Water Breathing","He is Doma's older brother","Demon Slayer",450],
  ["What is Tanjiro's earring design?","Hanafuda earrings (flower cards) - a family heirloom","Cherry blossom","Dragon scales","Flame patterns","Demon Slayer",350],
  ["Who is Akaza in Demon Slayer?","Upper Rank Three - loves martial arts and fights with Destructive Death","Upper Rank Two","The demon who killed Rengoku","The oldest demon besides Muzan","Demon Slayer",350],
  ["What is Muzan Kibutsuji's greatest weakness?","Sunlight and Wisteria poison","Silver weapons","Holy water","Fire attacks","Demon Slayer",300],
  ["What is Zenitsu's most powerful technique?","Thunderclap and Flash: Godspeed (seventh form)","First form only","Lightning Breath final form","Thunder God","Demon Slayer",450],
  # HxH
  ["What is the ability system in HxH called?","Nen","Ki","Chakra","Spiritual Pressure","HxH",200],
  ["What is Gon's father's name in HxH?","Ging Freecss","Killua's father","Isaac Netero","Pariston Hill","HxH",250],
  ["Who is Gon's best friend in HxH?","Killua Zoldyck","Kurapika","Leorio","Hisoka","HxH",200],
  ["What family is Killua from?","Zoldyck","Freecss","Phantom Troupe","Hunter family","HxH",250],
  ["What Nen type does Killua specialize in?","Transmutation","Emission","Enhancement","Manipulation","HxH",350],
  ["Who leads the Phantom Troupe in HxH?","Chrollo Lucilfer","Hisoka","Feitan","Uvogin","HxH",300],
  ["What is the name of Hisoka's Nen ability?","Bungee Gum","Texture Surprise","Bungee Cord","Rubber Glue","HxH",350],
  ["Who is the Chimera Ant king in HxH?","Meruem","Neferpitou","Shaiapouf","Menthuthuyoupi","HxH",300],
  ["What is Leorio's long-term goal in HxH?","To become a doctor","To find his father","To avenge his clan","To lead the Hunter Association","HxH",300],
  ["What is Gon's most powerful technique?","Jajanken (Rock, Scissors, Paper) with massive power","Nen Punch","Gon's Force","Hakoware","HxH",350],
  ["What is Killua's Godspeed technique?","He converts electricity into Nen allowing extreme speed and reaction","He becomes invisible","He stops time","He can fly","HxH",450],
  ["What is the Greed Island arc about?","An RPG video game where players are physically transported into the game","A training arc","A war arc","A rescue arc","HxH",350],
  ["What is the Chimera Ant arc about in HxH?","Ants that evolve by consuming humans and developing Nen abilities","A war arc","A tournament arc","A treasure hunt","HxH",400],
  # BLEACH
  ["What is Ichigo's main weapon in Bleach?","Zangetsu","Benihime","Senbonzakura","Zabimaru","Bleach",200],
  ["What is a Soul Reaper called in Japanese in Bleach?","Shinigami","Arrancar","Quincy","Fullbring","Bleach",200],
  ["Who is the main antagonist of the Soul Society arc in Bleach?","Sosuke Aizen","Yhwach","Ginjo","Grimmjow","Bleach",300],
  ["What is the final release of a Zanpakuto called?","Bankai","Shikai","Resurreccion","Vollstandig","Bleach",250],
  ["What are hollows who have regained humanoid form called?","Arrancar","Espada","Menos","Vasto Lorde","Bleach",350],
  ["What power do the Quincy have in Bleach?","Spirit Weapon (absorb spiritual particles)","Death energy","Soul surgery","Hollow power","Bleach",350],
  ["What is Byakuya Kuchiki's Bankai?","Senbonzakura Kageyoshi","Daiguren Hyorinmaru","Hakka no Togame","Kamishini no Yari","Bleach",350],
  ["What is Aizen's Zanpakuto ability?","Complete hypnosis of anyone who sees its shikai","Gravity manipulation","Time reversal","Telepathy","Bleach",400],
  ["What is the name of the Quincy king in Bleach?","Yhwach (Juha Bach)","Uryu Ishida","Bazz-B","Haschwalth","Bleach",400],
  ["Who is Ichigo's father and what is his secret?","Isshin Kurosaki - a former Soul Reaper captain","A Quincy","A Fullbringer","An Arrancar","Bleach",400],
  ["What is Ichigo's hollow form?","Hollow Ichigo / Vasto Lorde","Bankai form","True Zangetsu","White","Bleach",300],
  ["What is Squad 4 captain known for in Bleach?","Healing abilities (Unohana Retsu)","Offensive power","Swordsmanship","Kidou magic","Bleach",400],
  # JJK
  ["Who does Yuji Itadori become the vessel of in JJK?","Ryomen Sukuna","Mahito","Geto","Kenjaku","Jujutsu Kaisen",200],
  ["What is Gojo Satoru's technique in JJK?","Infinity and Limitless","Cursed Speech","Ratio","Projection Sorcery","Jujutsu Kaisen",250],
  ["What school do the main JJK characters attend?","Tokyo Jujutsu High","Kyoto Jujutsu High","Sendai Jujutsu High","Osaka Jujutsu","Jujutsu Kaisen",200],
  ["What is Megumi Fushiguro's technique in JJK?","Ten Shadows Technique","Boogie Woogie","Hairpin","Straw Doll","Jujutsu Kaisen",300],
  ["Who is the villain who manipulates bodies in JJK?","Mahito","Suguru Geto","Jogo","Hanami","Jujutsu Kaisen",300],
  ["What is Gojo's most powerful technique?","Hollow Purple (Blue plus Red)","Cursed Strike","Domain Expansion","Infinite Void","Jujutsu Kaisen",350],
  ["What is a Domain Expansion in JJK?","A barrier technique that guarantees attacks land","A cursed tool","A special grade curse","A binding vow","Jujutsu Kaisen",350],
  ["What are cursed spirits made of in JJK?","Negative emotions of humans","Cursed tools","Dead sorcerers","Binding vows","Jujutsu Kaisen",300],
  ["What is Toge Inumaki's cursed technique?","Cursed Speech","Ratio Technique","Flowing Red Scale","Divergent Fist","Jujutsu Kaisen",350],
  ["What does Gojo's Six Eyes allow in JJK?","See cursed energy flow at near zero consumption","See the past and future","See all emotions","See soul structure","Jujutsu Kaisen",450],
  ["Who is Kenjaku in JJK?","An ancient sorcerer who inhabits bodies by transplanting his brain","Suguru Geto's older identity","A demon king","Mahito's creator","Jujutsu Kaisen",450],
  ["What is Yuta Okkotsu's connection to Rika?","She is a vengeful spirit bound to him (his childhood friend who died)","She is his sister","She is an ancient curse","She is his shikigami","Jujutsu Kaisen",400],
  # POKEMON
  ["What are the three starter Pokemon in Generation 1?","Bulbasaur, Charmander, Squirtle","Chikorita, Cyndaquil, Totodile","Treecko, Torchic, Mudkip","Turtwig, Chimchar, Piplup","Pokemon",200],
  ["What is the first Pokemon in the National Pokedex?","Bulbasaur","Caterpie","Pidgey","Rattata","Pokemon",200],
  ["What type is Charizard?","Fire and Flying","Fire only","Dragon and Fire","Fire and Dragon","Pokemon",300],
  ["What move does Pikachu use most famously?","Thunderbolt","Thunder","Volt Tackle","Quick Attack","Pokemon",200],
  ["What is Mewtwo created from?","Mew's DNA","Ancient fossil","Genetic engineering alone","Ultra Beast","Pokemon",300],
  ["What does Eevee evolve into with a Water Stone?","Vaporeon","Jolteon","Flareon","Espeon","Pokemon",300],
  ["What types are effective against Dragon-types?","Ice, Dragon, and Fairy","Fire","Water","Electric","Pokemon",350],
  ["What Pokemon is known as The Original One?","Arceus","Dialga","Palkia","Giratina","Pokemon",350],
  ["What does Magikarp evolve into?","Gyarados","Lapras","Vaporeon","Kingdra","Pokemon",250],
  ["Who created Pokemon in the real world?","Satoshi Tajiri","Ken Sugimori","Junichi Masuda","Hironobu Sakaguchi","Pokemon",400],
  ["What are the Legendary birds of Generation 1?","Articuno, Zapdos, Moltres","Suicune, Raikou, Entei","Lugia, Ho-Oh, Celebi","Regice, Regirock, Registeel","Pokemon",300],
  ["What are the Legendary dogs of Generation 2?","Suicune, Raikou, Entei","Articuno, Zapdos, Moltres","Uxie, Mesprit, Azelf","Regice, Regirock, Registeel","Pokemon",350],
  ["What is the Pokemon associated with the creation of all things?","Arceus","Dialga","Palkia","Mew","Pokemon",350],
  # SAO
  ["What is the name of the main protagonist in SAO?","Kirito (Kazuto Kirigaya)","Asuna","Klein","Agil","SAO",200],
  ["What happens if you die in the first arc of SAO?","You die in real life","You wake up","You lose a level","You are trapped permanently","SAO",200],
  ["What is Kirito's unique ability in SAO?","Dual Wielding","Solo clearing","Speed","Alchemy","SAO",300],
  ["What VR game is the second arc of SAO set in?","ALfheim Online","Gun Gale Online","Underworld","Ordinal Scale","SAO",350],
  ["Who is the villain in the first arc of SAO?","Akihiko Kayaba (Heathcliff)","Sugou Nobuyuki","Death Gun","Gabriel Miller","SAO",400],
  ["What is Yui in SAO?","An AI mental health program posing as their daughter","A real player","A boss","A system NPC","SAO",350],
  ["What is the virtual world in SAO: Alicization called?","Underworld","ALO","GGO","Cardinal","SAO",400],
  ["Who is Alice in SAO: Alicization?","An Integrity Knight with recovered memories","Asuna's avatar","An AI like Yui","Kirito's sister","SAO",350],
  ["What is a Nerve Gear in SAO?","A VR headset that interfaces directly with the nervous system","A combat technique","A defensive skill","An in-game item","SAO",250],
  ["What is SAO: Mothers Rosario about?","Asuna's storyline centered on a terminally ill player named Yuuki","Kirito's new quest","A new death game","A Mother NPC storyline","SAO",400],
  # BERSERK
  ["What is Guts's enormous black sword called in Berserk?","Dragonslayer","Berserk Blade","Black Edge","Shadow Cutter","Berserk",250],
  ["Who is the leader of the Band of the Hawk in Berserk?","Griffith","Guts","Casca","Judeau","Berserk",250],
  ["What is the central tragedy event of Berserk?","The Eclipse","The Hundred-Year War","The Apostle Feast","The Brand Ceremony","Berserk",300],
  ["What does the Brand of Sacrifice mean in Berserk?","The branded are hunted by evil spirits forever","They can summon demons","They gain power","They are immortal","Berserk",350],
  ["Who created Berserk?","Kentaro Miura","Hirohiko Araki","Eiichiro Oda","Tite Kubo","Berserk",300],
  ["What is Griffith's God Hand form called in Berserk?","Femto","Void","Slan","Ubik","Berserk",400],
  ["What is Guts's Berserker Armor in Berserk?","Armor that pushes his body beyond limits, ignoring pain and injury","A magical suit that grants powers","An ancient artifact of the God Hand","A cursed armor that eats enemies","Berserk",450],
  # CODE GEASS
  ["What is Lelouch's power called in Code Geass?","Geass (power of absolute command)","Code","Knightmare Force","Requiem","Code Geass",200],
  ["What military unit does Lelouch lead in Code Geass?","Black Knights","Order of the Glorious","Zero Squad","Holy Knights","Code Geass",250],
  ["What country has conquered Japan in Code Geass?","Holy Britannian Empire","Europia United","Chinese Federation","U.F.N.","Code Geass",250],
  ["What is Japan renamed to under Britannian rule?","Area 11","Zone J","New Britannia East","District Tokyo","Code Geass",300],
  ["What is the Zero Requiem in Code Geass?","Lelouch becomes a tyrant then is killed to bring peace","A final battle plan","A peace treaty","A geass ritual","Code Geass",450],
  ["What mechanical weapons do pilots use in Code Geass?","Knightmare Frames","Mobile Suits","Evangelions","Titans","Code Geass",250],
  # SAILOR MOON
  ["What is Sailor Moon's real name?","Usagi Tsukino","Rei Hino","Ami Mizuno","Makoto Kino","Sailor Moon",200],
  ["What is the name of Usagi's talking cat in Sailor Moon?","Luna","Artemis","Diana","Chibi","Sailor Moon",200],
  ["Who is Tuxedo Mask in Sailor Moon?","Mamoru Chiba (Darien)","Motoki","Haruka","Seiya","Sailor Moon",250],
  ["Who is the main villain in the first Sailor Moon arc?","Queen Beryl","Wiseman","Pharaoh 90","Nehellenia","Sailor Moon",300],
  # ONE PUNCH MAN
  ["What is Saitama's problem in One Punch Man?","He defeats all enemies in one punch and feels no excitement","He is unranked","He has no friends","He cannot control his power","One Punch Man",200],
  ["Who is Saitama's cyborg disciple?","Genos","Mumen Rider","King","Tatsumaki","One Punch Man",250],
  ["Who is the S-Class Rank 1 hero in OPM?","Blast","Tatsumaki","Bang","Tornado","One Punch Man",350],
  ["Who is Garou in One Punch Man?","Hero Hunter who becomes a humanoid monster","S-Class hero","A villain general","A disciple of Saitama","One Punch Man",350],
  ["What is the monster villain association in OPM?","Monster Association","Villain Union","Dark Syndicate","Demon Club","One Punch Man",300],
  ["What is Tatsumaki's power in OPM?","Esper telekinesis (the most powerful esper alive)","Wind control","Psychokinesis","Force fields","One Punch Man",300],
  # DR. STONE
  ["Who is the main character of Dr. Stone?","Senku Ishigami","Taiju Oki","Tsukasa","Chrome","Dr. Stone",200],
  ["What is Senku's goal in Dr. Stone?","Rebuild civilization using science","Defeat Tsukasa","Find the cause of petrification","Explore the new world","Dr. Stone",300],
  ["What is the name of Senku's kingdom in Dr. Stone?","Kingdom of Science","Science Empire","New Civilization","Stone World Republic","Dr. Stone",300],
  ["Who opposes Senku in Dr. Stone?","Tsukasa Shishio","Chrome","Gen Asagiri","Ibara","Dr. Stone",300],
  # SLIME ISEKAI
  ["What is Rimuru Tempest's original form?","A slime","A dragon","A goblin","A wolf","Slime Isekai",200],
  ["What unique skill does Rimuru have from the start?","Predator (absorb and mimic abilities)","Ultimate Magic","Sage's Wisdom","Great Sage","Slime Isekai",300],
  ["What nation does Rimuru found?","Tempest (Jura Tempest Federation)","Rimuru Kingdom","Monster Republic","Goblin Nation","Slime Isekai",300],
  ["Who is the Storm Dragon who names Rimuru?","Veldora Tempest","Milim Nava","Ramiris","Diablo","Slime Isekai",300],
  # OVERLORD
  ["What is Ainz Ooal Gown's base in Overlord?","Nazarick (Great Tomb of Nazarick)","Ainzbel Castle","Overlord Citadel","Dark Sanctuary","Overlord",300],
  ["What was Ainz's player name in YGGDRASIL?","Momonga","Ainz","Supreme Being","Lord of Death","Overlord",350],
  ["What class is Ainz in Overlord?","Undead magic caster (Overlord)","Warrior","Paladin","Demon King","Overlord",300],
  ["Who is Albedo in Overlord?","Guardian Overseer of Nazarick who is deeply devoted to Ainz","The most powerful warrior","A mind controller","Ainz's sister","Overlord",300],
  # KONOSUBA
  ["What useless goddess does Kazuma choose in KonoSuba?","Aqua","Eris","Iris","Wiz","KonoSuba",200],
  ["What is Megumin specialized in?","Explosion magic (only one explosion per day)","All offensive magic","Water magic","Darkness spells","KonoSuba",250],
  ["What is Darkness's class in KonoSuba?","Crusader (masochistic tank)","Paladin","Knight","Warrior","KonoSuba",300],
  # VINLAND SAGA
  ["Who is Thorfinn's father in Vinland Saga?","Thors","Askeladd","Floki","Bjorn","Vinland Saga",300],
  ["What land do characters seek in Vinland Saga?","Vinland","Britannia","Frankia","Iceland","Vinland Saga",300],
  ["Who kills Thors in Vinland Saga?","Askeladd (under orders from Floki)","Thorkell","Canute","King Sweyn","Vinland Saga",350],
  # RE:ZERO
  ["What is Subaru's ability in Re:Zero?","Return by Death (respawn at a checkpoint when killed)","Time manipulation","Invisibility","Future sight","Re:Zero",200],
  ["Who is the silver-haired half-elf Subaru meets first?","Emilia","Beatrice","Rem","Ram","Re:Zero",200],
  ["What is Rem's weapon?","A morning star (iron ball flail)","A sword","A lance","Magic only","Re:Zero",300],
  ["What is the name of the Witch of Greed in Re:Zero?","Echidna","Satella","Carmilla","Typhon","Re:Zero",350],
  ["What is the Witch of Envy's name in Re:Zero?","Satella","Echidna","Sekhmet","Minerva","Re:Zero",350],
  ["What are sin archbishops of the Witch Cult in Re:Zero?","Bishops wielding Authority (e.g., Sloth, Lust)","Witch's servants","Demon lords","Archdemons","Re:Zero",400],
  # STEINS;GATE
  ["What does Okabe Rintaro call himself?","Hououin Kyouma","The Time Lord","Future Gadget Man","El Psy Kongroo","Steins;Gate",300],
  ["What device does the lab accidentally create in Steins;Gate?","A microwave that can send messages to the past","A time machine","A teleporter","A memory eraser","Steins;Gate",250],
  ["What is Kurisu Makise famous for in Steins;Gate?","Publishing a paper on time travel at age 18","Inventing the Phone Microwave","Creating SERN","Being Okabe's childhood friend","Steins;Gate",350],
  ["Who is Suzuha Amane in Steins;Gate?","A time traveler from the future (John Titor)","Kurisu's sister","A SERN agent","Daru's old friend","Steins;Gate",400],
  ["What is the Steins Gate world line?","The timeline where all characters survive (divergence ~1.048596%)","The dystopian future","The original timeline","The war timeline","Steins;Gate",450],
  # BLACK CLOVER
  ["What is Asta's unique power in Black Clover?","Anti-magic (he has no magic power)","Black magic","Forbidden magic","Time magic","Black Clover",200],
  ["What guild does Asta join in Black Clover?","Black Bulls","Golden Dawn","Silver Eagles","Green Praying Mantises","Black Clover",200],
  ["Who is the Wizard King at the start of Black Clover?","Julius Novachrono","Yami Sukehiro","Fuegoleon Vermillion","Marx","Black Clover",300],
  ["What magic does Yami Sukehiro use?","Dark Magic","Shadow Magic","Void Magic","Black Hole Magic","Black Clover",350],
  ["What is Noelle's magic in Black Clover?","Water Magic","Wind Magic","Ice Magic","Spirit Magic","Black Clover",250],
  ["What is Yuno's spirit in Black Clover?","Bell (a wind spirit)","Undine (water spirit)","Salamander (fire spirit)","Sylph (wind spirit)","Black Clover",350],
  ["What is the name of the Devil bound to Asta's grimoire?","Liebe","Zagred","Lucifero","Megicula","Black Clover",400],
  # SPY x FAMILY
  ["What is Loid Forger's spy codename?","Twilight","Franky","Nightfall","Handler","Spy x Family",200],
  ["What is Anya's secret ability?","She can read minds (telepathy)","She can see the future","She can turn invisible","She has super strength","Spy x Family",200],
  ["What school does Anya try to get into?","Eden Academy","Berlint University","Swan School","Imperial Garden","Spy x Family",250],
  ["What is Yor Briar's secret identity?","An assassin called Thorn Princess","A spy handler","A government informant","A former soldier","Spy x Family",250],
  ["What is the name of Anya's pet dog?","Bond","Rex","Spy","Hound","Spy x Family",250],
  ["What special ability does Bond have?","He can see the future","He can detect bombs","He is a trained guard dog","He is telepathic","Spy x Family",350],
  # FAIRY TAIL
  ["What is Natsu's fire magic called?","Fire Dragon Slayer Magic","Fire God Slayer","Flame Mage","Dragon Force","Fairy Tail",200],
  ["What guild do the main characters belong to?","Fairy Tail","Blue Pegasus","Sabertooth","Lamia Scale","Fairy Tail",200],
  ["What is Erza Scarlet's magic type?","Requip (The Knight)","Gravity Change","Ice Make","Celestial Spirit","Fairy Tail",250],
  ["What is Lucy's magic in Fairy Tail?","Celestial Spirit Magic","Re-quip","Stellar Magic","Star Break","Fairy Tail",200],
  ["Who is the dragon who raised Natsu?","Igneel","Atlas Flame","Grandeeney","Metalicana","Fairy Tail",300],
  ["Who is Zeref in Fairy Tail?","The Black Wizard","The Dark Lord","The Dragon King","The Demon God","Fairy Tail",300],
  ["Who is the founding guild master of Fairy Tail?","Mavis Vermillion","Erza Scarlet","Gildarts Clive","Laxus Dreyar","Fairy Tail",350],
  ["What is Gray's magic in Fairy Tail?","Ice Make","Ice God Slayer","Arctic Blast","Freeze magic","Fairy Tail",250],
  # VIOLET EVERGARDEN
  ["What is Violet Evergarden's job after the war?","Auto Memory Doll (letter writer)","Soldier","Nurse","Royal scribe","Violet Evergarden",200],
  ["What were the last words Gilbert said to Violet?","I love you","Live your life","Serve the empire","Find your purpose","Violet Evergarden",300],
  ["Who is Violet's commanding officer she is devoted to?","Gilbert Bougainvillea","Dietfried","Claudia Hodgins","Leon Stephanotis","Violet Evergarden",250],
  ["What is Violet trying to understand throughout the series?","What 'I love you' means","How to use prosthetics","What peace feels like","Who her parents were","Violet Evergarden",300],
  # YOUR NAME
  ["What is the phenomenon that connects the two characters in Your Name?","They switch bodies while sleeping","They share dreams","They see each other's past","They communicate through letters","Your Name",200],
  ["What comet is central to the plot of Your Name?","Tiamat","Halley's Comet","Mia Comet","Celestia","Your Name",350],
  ["Who directed Your Name?","Makoto Shinkai","Hayao Miyazaki","Mamoru Hosoda","Satoshi Kon","Your Name",300],
  # SPIRITED AWAY
  ["What is the name of the main character in Spirited Away?","Chihiro","Sen","Yubaba","Haku","Spirited Away",200],
  ["Who is Haku's true identity in Spirited Away?","The spirit of the Kohaku River","A dragon demon","A lost boy","A god of storms","Spirited Away",350],
  ["Who directed Spirited Away?","Hayao Miyazaki","Makoto Shinkai","Mamoru Hosoda","Isao Takahata","Spirited Away",250],
  ["What award did Spirited Away win?","Academy Award for Best Animated Feature","Palme d'Or","BAFTA only","Golden Globe only","Spirited Away",300],
  ["What creature eats everything and grows large in Spirited Away?","No-Face","Yubaba's baby","The River God","Kamaji","Spirited Away",350],
  # NGE
  ["What are the big mechs in NGE called?","Evangelion Units (Evas)","Mecha Units","Titans","Angels","NGE",200],
  ["Who is the pilot of Eva Unit 02?","Asuka Langley Soryu","Rei Ayanami","Shinji Ikari","Misato","NGE",250],
  ["What is Rei Ayanami's secret origin?","She is a clone of Shinji's mother Yui","She is an Angel hybrid","She is an AI","She is Gendo's daughter","NGE",400],
  ["What is the Human Instrumentality Project in NGE?","The merging of all human souls into one","An Eva weapons program","The destruction of all Angels","A terraforming plan","NGE",400],
  ["Who is Kaworu Nagisa in NGE?","The final Angel (Tabris) who befriends Shinji","A NERV scientist","Asuka's love interest","A clone like Rei","NGE",400],
  ["What organization funds NERV in NGE?","SEELE","WILLE","UN Special Agency","Gehirn","NGE",350],
  # CHAINSAW MAN
  ["What is Denji's Devil partner in Chainsaw Man?","Pochita (the Chainsaw Devil)","Power (Blood Devil)","Aki (Fox Devil)","Makima (Control Devil)","Chainsaw Man",200],
  ["Who is the main female villain of Part 1 in Chainsaw Man?","Makima","Quanxi","Santa Claus","Reze","Chainsaw Man",300],
  ["What does Makima's ability do in Chainsaw Man?","Control anyone weaker than her","Read minds","Create devils","Erase memories","Chainsaw Man",350],
  ["What organization does Denji work for?","Public Safety Devil Hunters","Private Devil Hunters","Devil Corps","Fiend Task Force","Chainsaw Man",250],
  ["What is Asa Mitaka's power in Chainsaw Man Part 2?","She can turn people into weapons (War Devil's ability)","She is a normal human","She controls Chainsaw Man","She has the Death Devil","Chainsaw Man",450],
  # GURREN LAGANN
  ["What is Kamina's role in Gurren Lagann?","Simon's older brother figure and the face of Team Gurren","The final villain","A mech pilot who survives","The Anti-Spiral king","Gurren Lagann",300],
  ["What is Spiral Power in Gurren Lagann?","Energy generated by life's will to evolve","Solar energy","Magical power","Anti-matter","Gurren Lagann",350],
  ["What is the name of the final mech in Gurren Lagann?","Super Tengen Toppa Gurren Lagann","Arc-Gurren Lagann","Dai-Gurren","Ultimate Spiral","Gurren Lagann",400],
  # MOB PSYCHO
  ["What is Mob's real name in Mob Psycho 100?","Shigeo Kageyama","Reigen Arataka","Ritsu Kageyama","Dimple","Mob Psycho",200],
  ["What is Mob's psychic ability?","Extremely powerful telekinesis and ESP","Mind control only","Elemental magic","Ghost summoning","Mob Psycho",250],
  # PARASYTE
  ["Where do parasites typically take over a host in Parasyte?","The brain","The heart","The hands","The liver","Parasyte",300],
  ["What is the name of the parasite who bonds with Shinichi?","Migi","Hideo","Reiko","Ryoko","Parasyte",250],
  # YOUR LIE IN APRIL
  ["Who is Kousei Arima in Your Lie in April?","A pianist who cannot hear the music after his mother's death","A violinist","A cellist","A singer","Your Lie in April",300],
  # SHIELD HERO
  ["What is Naofumi's hero weapon in Shield Hero?","Shield","Spear","Sword","Bow","Shield Hero",200],
  ["What is the name of the main female companion in Shield Hero?","Raphtalia","Filo","Glass","Melty","Shield Hero",250],
  ["What is Filo in Shield Hero?","A filolial (bird creature) who can transform into a girl","A fairy","An elf","A human child","Shield Hero",350],
  # HAIKYUU
  ["What sport is Haikyuu about?","Volleyball","Basketball","Soccer","Baseball","Haikyuu",200],
  ["What is the name of Hinata Shoyo's high school team?","Karasuno High","Nekoma High","Fukurodani High","Aoba Josai High","Haikyuu",250],
  ["What is the rivalry between Karasuno and Nekoma called?","The Battle of the Trash Heap","The Cat vs Crow rivalry","The Classic Grudge","The Eternal Match","Haikyuu",400],
  # YURI ON ICE
  ["What sport is featured in Yuri on Ice?","Figure skating","Ice hockey","Speed skating","Curling","Yuri on Ice",200],
  ["Who is Victor Nikiforov in Yuri on Ice?","Russia's legendary figure skater who coaches Yuri","A rival","A judge","An ice dancer","Yuri on Ice",250],
  # INITIAL D
  ["What type of racing is featured in Initial D?","Touge (mountain pass) racing","Street drag racing","Formula racing","Rally racing","Initial D",300],
  ["What car does Takumi Fujiwara drive in Initial D?","Toyota AE86 Trueno (Hachi-Roku)","Mazda RX-7","Mitsubishi Lancer Evo","Nissan Skyline GT-R","Initial D",350],
  # HARUHI SUZUMIYA
  ["What is the SOS Brigade in Haruhi Suzumiya?","A club Haruhi creates to find aliens, time travelers, and espers","A school council","A science club","An anime club","Haruhi Suzumiya",300],
  ["What is Haruhi's unknowing power?","She can unconsciously reshape reality","She can read minds","She can time travel","She is an alien","Haruhi Suzumiya",400],
  # K-ON
  ["What instrument does Yui play in K-On?","Guitar","Bass","Drums","Keyboard","K-On",250],
  ["What is the name of the K-On school band?","Ho-kago Tea Time (After School Tea Time)","Light Music Club Band","K-On Band","Sakura High Group","K-On",300],
  # FRUITS BASKET
  ["What curse does the Sohma family have?","Members transform into animals of the Chinese zodiac","They cannot love","They age backwards","They have visions","Fruits Basket",250],
  ["What zodiac animal does Kyo Sohma turn into?","Cat (excluded from the zodiac)","Dog","Tiger","Wolf","Fruits Basket",300],
  ["Who is Tohru Honda in Fruits Basket?","An optimistic orphan girl who lives with the Sohmas","A Sohma family member","A cursed girl","A school counselor","Fruits Basket",250],
  # SOUL EATER
  ["What is Death the Kid's obsession in Soul Eater?","Perfect symmetry","Skulls","Strength","Speed","Soul Eater",300],
  ["What is the DWMA in Soul Eater?","Death Weapon Meister Academy - trains meisters and weapons","Death World Military Academy","Dark Weapon Masters Association","Devil Weapon Mastery Academy","Soul Eater",250],
  # ASSASSINATION CLASSROOM
  ["Why cannot the government destroy Koro-sensei?","He threatens to blow up Earth if harmed and class 3-E must kill him","He is invincible","He is invisible","He controls all weapons","Assassination Classroom",300],
  # KAKEGURUI
  ["What is the school in Kakegurui famous for?","Students resolve everything through gambling","Academic excellence","Political connections","Sports achievements","Kakegurui",300],
  ["What is Yumeko Jabami in Kakegurui?","A transfer student who gambles for the thrill","The student council president","A rich heiress hiding her gambling","A professional gambler","Kakegurui",300],
  # SAIKI K
  ["What is Saiki K's power?","He has virtually every psychic power","He can read minds only","He can time travel only","He has telekinesis only","Saiki K",250],
  # OREGAIRU
  ["What is the Service Club in Oregairu?","A club that helps students with problems","A student council","A social club","A study group","Oregairu",300],
  ["Who is Hikigaya Hachiman in Oregairu?","A cynical antisocial high schooler who is secretly insightful","A popular jock","A class president","A romance-seeking protagonist","Oregairu",300],
  # OSHI NO KO
  ["What is the central mystery in Oshi no Ko?","Who murdered Ai Hoshino","Why Aqua was reincarnated","What B-Komachi's secret is","Who Ruby's real father is","Oshi no Ko",350],
  ["What is Ai Hoshino's secret in Oshi no Ko?","She had two children (Aqua and Ruby) before becoming famous","She was already married","She had a criminal past","She faked her death","Oshi no Ko",400],
  # MADOKA MAGICA
  ["Who is the main antagonist in Madoka Magica?","Kyubey (the true antagonist)","Walpurgisnacht","Mami Tomoe","Homura Akemi","Madoka",300],
  ["What is a magical girl's soul transferred to?","A Soul Gem","A wish crystal","A transformation brooch","A Grief Seed","Madoka",300],
  ["What is a Witch in Madoka Magica?","A corrupted magical girl whose Soul Gem became a Grief Seed","A rival magical girl","An enemy alien","A demon","Madoka",400],
  ["What wish does Madoka ultimately make?","To erase all witches across all timelines before they are born","To become a magical girl","To save Homura","To reset time","Madoka",500],
  ["Who is Homura Akemi in Madoka Magica?","A time-looping magical girl trying to save Madoka","A veteran magical girl","A witch hunter","Kyubey's partner","Madoka",400],
  # PSYCHO-PASS
  ["What is the Sibyl System in Psycho-Pass?","An AI system that measures criminal potential in citizens","A law enforcement agency","A brain scanner","A judicial computer","Psycho-Pass",300],
  ["Who is Akane Tsunemori in Psycho-Pass?","A rookie MWPSB inspector with an exceptionally clear Psycho-Pass","A veteran enforcer","A Sibyl System analyst","A criminally asymptomatic person","Psycho-Pass",300],
  # TOKYO REVENGERS
  ["What is Tokyo Revengers about?","A man travels back in time to save his girlfriend from a gang","A delinquent gang war","A time travel romance","A yakuza story","Tokyo Revengers",300],
  ["What is Takemichi Hanagaki's ability?","Time leaping to the past when he shakes hands with Naoto","Future sight","Mind control","Superhuman strength","Tokyo Revengers",350],
  # BLUE LOCK
  ["What is Blue Lock about?","A football program to create a world-class striker for Japan","A hockey program","A basketball training camp","A martial arts school","Blue Lock",300],
  # BUNGO STRAY DOGS
  ["What is Bungo Stray Dogs about?","People with powers based on famous authors fighting crime and mysteries","A detective agency alone","Literary characters come to life","A school for gifted writers","Bungo Stray Dogs",300],
  ["What is Osamu Dazai's ability in Bungo Stray Dogs?","No Longer Human - nullify any supernatural ability by touch","Super speed","Mind control","Teleportation","Bungo Stray Dogs",350],
  # DURARARA
  ["Who is the Headless Rider in Durarara?","Celty Sturluson (a Dullahan)","Shizuo Heiwajima","Izaya Orihara","Mikado Ryugamine","Durarara",350],
  ["What is Izaya Orihara in Durarara?","An information broker who loves humans and manipulates events","A gang leader","A detective","A police informant","Durarara",350],
  # MADE IN ABYSS
  ["What is the Curse of the Abyss in Made in Abyss?","Going deeper causes severe physical effects when ascending","A monster summoning curse","A relic activation risk","A blessing in disguise","Made in Abyss",400],
  ["What is Reg in Made in Abyss?","A robot with no memories who accompanies Riko into the Abyss","A human boy","An Abyss guardian","A cave raider","Made in Abyss",300],
  ["What is Riko's goal in Made in Abyss?","To descend to the bottom of the Abyss to find her mother Lyza","To become a White Whistle","To map the Abyss","To escape the Abyss with Reg","Made in Abyss",350],
  # MUSHISHI
  ["What are Mushi in Mushishi?","Primitive life forms at the boundary of life","Spirits","Demons","Ghosts","Mushishi",300],
  # SAMURAI CHAMPLOO
  ["What music genre is Samurai Champloo famous for mixing with samurai?","Hip-hop","Jazz","Rock","Blues","Samurai Champloo",300],
  ["Who directed Samurai Champloo?","Shinichiro Watanabe","Makoto Shinkai","Masahiro Ando","Hiroshi Hamasaki","Samurai Champloo",400],
  # YU YU HAKUSHO
  ["What is Yusuke Urameshi in Yu Yu Hakusho?","A delinquent who becomes a Spirit Detective","A demon","A human fighter","A ghost","Yu Yu Hakusho",200],
  ["What is Kurama's rose weapon in Yu Yu Hakusho?","Rose Whip","Thorn Blade","Petal Strike","Silver Vine","Yu Yu Hakusho",350],
  ["Who is Hiei in Yu Yu Hakusho?","A fire demon with a Jagan eye","A wind master","A water demon","A human psychic","Yu Yu Hakusho",300],
  ["What is the Dark Tournament in Yu Yu Hakusho?","A fighting tournament where Yusuke and his team compete against demons","A World Championship","A Spirit World qualifier","A demons-only tournament","Yu Yu Hakusho",300],
  # RUROUNI KENSHIN
  ["What is Kenshin's sword style?","Hiten Mitsurugi-ryu","Battojutsu","Kamiya Kasshin-ryu","Nirvana Blade","Rurouni Kenshin",350],
  ["What is Kenshin's reverse-blade sword called?","Sakabato","Nodachi","Katana-kaeshi","Zanpakuto","Rurouni Kenshin",400],
  # FATE
  ["What are Servants in the Fate series?","Heroic spirits summoned to fight in the Holy Grail War","Magical weapons","Magical familiars","Divine beings","Fate",250],
  ["What is the Holy Grail War in Fate series?","A battle royale where Masters and Servants fight for the Holy Grail","A tournament of mages","A divine ritual","A war between nations","Fate",250],
  ["Who is Saber in Fate/stay night?","Artoria Pendragon (King Arthur as a woman)","Merlin","Lancelot","Bedivere","Fate",350],
  ["Who is Gilgamesh in Fate series?","The King of Heroes - the oldest and most powerful Servant","A Berserker class Servant","A Caster class Servant","A Rider class Servant","Fate",400],
  ["What is the Gate of Babylon in Fate series?","Gilgamesh's treasury that fires legendary weapons as projectiles","A teleportation gate","A reality marble","A divine curse","Fate",400],
  ["What is Unlimited Blade Works in Fate/stay night?","Shirou's reality marble creating infinite swords","A sword technique","A magical barrier","A divine blessing","Fate",450],
  ["Who is Emiya Kiritsugu in Fate/Zero?","Shirou's adoptive father and a ruthless mage killer","A government agent","The main hero","Saber's husband","Fate",350],
  # KILL LA KILL
  ["What is Ryuko Matoi's main weapon in Kill la Kill?","A scissors blade given by her father","A magical sword","Energy whips","A giant scissors","Kill la Kill",250],
  ["What is Senketsu in Kill la Kill?","A talking Kamui (Life Fiber uniform) that bonds with Ryuko","A magical weapon","A robot companion","A voice in Ryuko's head","Kill la Kill",300],
  ["What are Life Fibers in Kill la Kill?","Alien parasitic threads woven into clothing that grant power","Magical threads","Spiritual energy cords","Government technology","Kill la Kill",350],
  # JOJO
  ["What is DIO's famous technique in JoJo's Bizarre Adventure?","The World (Za Warudo) - time stop","Silver Chariot speed","Crazy Diamond healing","Gold Experience","JoJo",300],
  ["What are Stands in JoJo's Bizarre Adventure?","Spiritual entities that fight for their users","Physical powers","Demon contracts","Ancient techniques","JoJo",250],
  ["Who is the protagonist of JoJo Part 4?","Josuke Higashikata","Joseph Joestar","Jotaro Kujo","Giorno Giovanna","JoJo",300],
  ["What is Giorno Giovanna's dream in JoJo Part 5?","To become a Gang-Star (Capo of Passione)","To defeat DIO","To protect his friends","To restore his family name","JoJo",350],
  ["What is Killer Queen's ability in JoJo Part 4?","Turn things into bombs","Create barriers","Generate electricity","Erase memories","JoJo",400],
  ["What is the final form of Giorno's Stand?","Gold Experience Requiem - nullifies all actions and will","Gold Experience Overpower","Requiem Rush","Ultimate Gold","JoJo",450],
  ["Who is Yoshikage Kira in JoJo Part 4?","A serial killer obsessed with women's hands who wants a quiet life","A thief","A mob boss","A detective","JoJo",400],
  # GINTAMA
  ["Who is Gintoki Sakata in Gintama?","A samurai with natural wavy silver hair who runs odd jobs","A government samurai","A former ninja","A bounty hunter","Gintama",300],
  ["What is the setting of Gintama?","Feudal Japan invaded by aliens (Amanto)","Space in the future","Alternate modern Japan","Medieval fantasy Japan","Gintama",300],
  ["What is the Joui War in Gintama?","The war against alien invaders where Gintoki fought as the White Demon","A samurai civil war","An interplanetary conflict","A revolution","Gintama",450],
  # ANOHANA
  ["What is Anohana about?","A group of childhood friends reuniting to grant a dead friend's wish","A ghost romance","A supernatural horror","A time travel mystery","Anohana",250],
  # CLANNAD
  ["Who is the main female character in Clannad?","Nagisa Furukawa","Tomoyo Sakagami","Kotomi Ichinose","Kyou Fujibayashi","Clannad",250],
  # INUYASHA
  ["What is the Shikon Jewel in Inuyasha?","Jewel of Four Souls","Soul Crystal","Demon Gem","Sacred Jewel","Inuyasha",250],
  ["Who is the main protagonist in Inuyasha?","Inuyasha (half-dog demon)","Miroku","Shippo","Kohaku","Inuyasha",200],
  ["Who is the main villain in Inuyasha?","Naraku","Sesshomaru","Koga","Kikyo","Inuyasha",300],
  # COWBOY BEBOP
  ["Who composed the famous Cowboy Bebop soundtrack?","Yoko Kanno","Joe Hisaishi","Masashi Hamauzu","Norihiro Tsuru","Cowboy Bebop",400],
  ["What is the opening theme of Cowboy Bebop?","Tank!","Blue","The Real Folk Blues","Space Lion","Cowboy Bebop",300],
  ["What is the name of the dog on the Bebop?","Ein","Spike","Yin","Jack","Cowboy Bebop",250],
  ["What is Spike Spiegel's fighting style?","Jeet Kune Do","Brazilian Jiu-Jitsu","Muay Thai","Wing Chun","Cowboy Bebop",350],
  ["What is the last word Spike says at the end of Cowboy Bebop?","Bang","See you space cowboy","I'm not gonna die here","Real folk blues","Cowboy Bebop",400],
  # PROMISED NEVERLAND
  ["What is Grace Field House in The Promised Neverland?","An orphanage secretly a farm for demon food","A government facility","A school for gifted children","An underground city","Promised Neverland",250],
  ["Who are the three child protagonists of The Promised Neverland?","Emma, Norman, and Ray","Emma, Phil, and Don","Norman, Ray, and Gilda","Emma, Conny, and Ray","Promised Neverland",300],
  # LOG HORIZON
  ["What is the setting of Log Horizon?","Players of the MMORPG Elder Tale are trapped in the game world","A fantasy MMO world","A government virtual reality program","A simulation experiment","Log Horizon",300],
  ["Who is Shiroe in Log Horizon?","The Villain in Glasses - a strategist enchanter who organizes the trapped players","The strongest player","A game developer","A villain","Log Horizon",350],
  # PING PONG
  ["What is Ping Pong the Animation about?","Two friends with contrasting styles playing table tennis","International tennis","A ping pong robot","A school ping pong tournament","Ping Pong",300],
  # LITTLE WITCH ACADEMIA
  ["What is Little Witch Academia about?","A girl without innate magic enrolling in a witch academy inspired by a famous witch","A school for demons","A magical girl transformation show","A witch detective story","Little Witch Academia",250],
  ["Who is Shiny Chariot in Little Witch Academia?","A famous performing witch who inspired Atsuko (Akko)","The main villain","A teacher at Luna Nova","A legendary witch from history","Little Witch Academia",300],
  # DARLING IN THE FRANXX
  ["What is Darling in the FranXX about?","Teenagers pilot mecha called FranXX to fight monsters called Klaxosaurs","A romance in space","A dystopian survival show","A school battle royale","Darling in the FranXX",300],
  ["Who is Zero Two in Darling in the FranXX?","A klaxosaur hybrid who pilots with Hiro (a human)","A full klaxosaur","An Android pilot","A government weapon","Darling in the FranXX",300],
  # 86
  ["What is 86 about?","A war where a republic uses disposable 86 pilots against the Giadian Empire","A mecha tournament","A dystopian school survival","A space opera","86",300],
  ["Who is Shinei Nouzen in 86?","The Handler of the Spearhead Squadron called the Undertaker","The Vladilena Milize strategist","A Giadian pilot","A Republic commander","86",350],
  # NATSUME BOOK OF FRIENDS
  ["What is Natsume Takashi's ability?","He can see spirits and inherited his grandmother's book of spirit names","He can defeat spirits","He can enter spirit realm","He can purify spirits","Natsume Book of Friends",300],
  # ELFEN LIED
  ["What is Diclonii's special ability in Elfen Lied?","Invisible arms called vectors that can cut through anything","Psychic powers","Elemental control","Mind control","Elfen Lied",350],
  ["Who is Lucy in Elfen Lied?","A Diclonius with a split innocent personality called Nyu","A human girl","A government experiment","A demon hybrid","Elfen Lied",300],
  # AKAME GA KILL
  ["What are Teigu in Akame ga Kill?","Powerful relics and weapons with unique abilities","Legendary swords only","Magic spells","Military ranks","Akame ga Kill",300],
  ["What is Akame's special power in Akame ga Kill?","Her sword Murasame kills with one cut by spreading lethal poison","She is supernaturally fast","She has no Teigu but extraordinary skill","She can copy others' Teigu","Akame ga Kill",350],
  # BLACK BUTLER
  ["What is Sebastian Michaelis in Black Butler?","A demon butler contracted to Ciel Phantomhive","A human servant","A fallen angel","A noble spy","Black Butler",250],
  ["What does Sebastian want in exchange for serving Ciel?","Ciel's soul after his revenge is complete","Ciel's wealth","His freedom","Nothing","Black Butler",300],
  # OURAN
  ["What is Tamaki Suoh's role in Ouran High School Host Club?","King of the Host Club (founder)","School president","Richest student","Secret heir","Ouran",250],
  ["What breaks causing Haruhi's debt to the Host Club?","A vintage vase worth 8 million yen","A guitar","A window","A table","Ouran",250],
  # FIST OF THE NORTH STAR
  ["What is Fist of the North Star about?","Kenshiro a martial artist in a post-apocalyptic world avenging his fiancee","A samurai in feudal Japan","A space opera","A fantasy quest","Fist of the North Star",300],
  ["What is Kenshin's famous technique in FotNS?","Hokuto Shinken - strikes hidden pressure points causing bodies to explode","Hadoken energy blast","Spirit Bomb","Iron Fist technique","Fist of the North Star",350],
  ["What is Fist of the North Star's famous catchphrase?","You are already dead (Omae wa mou shindeiru)","You will not survive this","Feel the fist of the north star","Death comes for you","Fist of the North Star",300],
  # ANGEL BEATS
  ["What is Angel Beats! about?","Souls in a purgatory school fighting against God","A ghost high school","A Heaven school","A dream world","Angel Beats",300],
  # DARKER THAN BLACK
  ["What are Contractors in Darker than Black?","People with supernatural abilities who must pay a remuneration","Mercenary soldiers","Government agents","Alien hybrids","Darker than Black",350],
  ["What is the main character's power in Darker than Black?","Hei (BK-201) has electromagnetism powers","Ice powers","Detective skills with no powers","Heat vision","Darker than Black",350],
  # FREE
  ["What sport is Free! about?","Competitive swimming","Diving","Water polo","Synchronized swimming","Free",200],
  # WOTAKOI
  ["What is Wotakoi about?","Adult office workers who are otaku and start dating","Anime rivals who fall in love","A gamer and cosplayer who hate each other","College sweethearts reuniting","Wotakoi",350],
  # ORE MONOGATARI
  ["What is Ore Monogatari!! about?","A large muscular boy with a pure heart finding love","A shy girl romance","A sports romance","A delinquent love story","Ore Monogatari",300],
  # HYOUKA
  ["What is Hyouka about?","A high school student solving mysteries with the Classic Literature Club","A cooking competition","A romance drama","A sports tournament","Hyouka",300],
  # CLANNAD (additional)
  ["What is the Dango Daikozoku in Clannad?","A family of dango creatures from Nagisa's favorite visual novel/anime ending theme","A game within the show","Tomoya's childhood book","Nagisa's play","Clannad",350],
  # SHAMAN KING
  ["Who is Yoh Asakura in Shaman King?","A shaman who aims to become the Shaman King","A spirit hunter","A demon slayer","A ghost whisperer","Shaman King",250],
  # D.GRAY-MAN
  ["What are Akuma in D.Gray-man?","Weapons made from souls of the dead","Demons","Clones","AI weapons","D.Gray-man",300],
  ["What is Allen Walker's power in D.Gray-man?","His left arm is an Anti-Akuma weapon called Innocence","He can control Akuma","He has Innocence eyes","He is a Noah","D.Gray-man",350],
  # CARDCAPTOR SAKURA
  ["What are the cards in Cardcaptor Sakura called?","Clow Cards (later Sakura Cards)","Star Cards","Magic Cards","Spirit Cards","Cardcaptor",250],
  ["Who made the Clow Cards?","Clow Reed","Sakura","Cerberus","Yue","Cardcaptor",350],
  # TORADORA
  ["Who is the Palmtop Tiger in Toradora?","Taiga Aisaka","Minori Kushieda","Ami Kawashima","Sumire Kano","Toradora",250],
  ["Who is the male protagonist of Toradora?","Ryuji Takasu","Yusaku Kitamura","Haruta Masuo","Kouji Haruta","Toradora",250],
  # NANA
  ["What type of music does Nana Osaki perform?","Punk rock","Pop","Jazz","Classical","Nana",350],
  # ANCIENT MAGUS BRIDE
  ["What is Chise Hatori's ability in The Ancient Magus Bride?","She is a Sleigh Beggy who can absorb and release magical energy","She can talk to animals","She can see the future","She can control elements","Ancient Magus Bride",300],
  # MAHOUKA
  ["What is Tatsuya Shiba's ability in Mahouka?","Decomposition and Regrowth - he can reconstruct anything","Perfect magic casting","Future prediction","Invincibility","Mahouka",350],
  # DANMACHI
  ["What does Bell Cranel's skill Liaris Freese do?","He grows faster in stats the stronger the opponent he faces","Magic boost","Combat arts","Charm resistance","DanMachi",400],
  ["What is the Hestia Familia in DanMachi?","The familia Bell joins under the goddess Hestia","A mercenary guild","A mage school","A crafting guild","DanMachi",250],
  # HIGURASHI
  ["What is the mystery in Higurashi?","A murder curse in the village of Hinamizawa every year","A haunted school","A ghost story","A demon family","Higurashi",300],
  ["What is Rika's curse in Higurashi?","She is killed every year in June and relives time loops","She is possessed","She cannot leave the village","She ages backwards","Higurashi",400],
  # KUROKO'S BASKETBALL
  ["What is Kuroko's ability in Kuroko's Basketball?","Misdirection - he is nearly invisible on court","Super speed","Incredible shooting","Perfect defense","Kuroko Basketball",350],
  ["What is the Generation of Miracles in Kuroko's Basketball?","Five prodigies from Teiko Middle School","A team of all-star players","A recruitment program","A training regimen","Kuroko Basketball",300],
  # ADDITIONAL MISC
  ["What is Nana Osaki's band name in Nana?","BLAST","Trapnest","Sugar Rush","Black Rock Shooter","Nana",400],
  ["What is the setting of No Game No Life?","A world where everything is decided by games","A school where games are illegal","An RPG world","A game simulation","No Game No Life",300],
  ["What are Sora and Shiro called together in No Game No Life?","Blank","[ ] (brackets)","White","Kuuhaku","No Game No Life",300],
  ["What are the Ten Pledges in No Game No Life?","Rules that forbid violence and decide all conflict by games","The game laws","Tet's rules","Divine games","No Game No Life",400],
  ["What is the setting of Konosuba?","A fantasy world Kazuma is reincarnated into after dying","A virtual reality game","A dream world","A parallel universe","KonoSuba",200],
  ["What is the Toman gang in Tokyo Revengers?","Tokyo Manji Gang - a delinquent gang Takemichi joins in the past","A yakuza family","A police special unit","A biker gang","Tokyo Revengers",350],
  ["What is Yoichi Isagi's special ability in Blue Lock?","Spatial awareness and adapting by copying others' skills","Perfect shooting accuracy","Superhuman speed","Indestructible body","Blue Lock",350],
  ["What is the ability of Fyodor Dostoevsky in Bungo Stray Dogs?","Crime and Punishment - kills with a single touch","Manipulating others' crimes","Perfect strategy","Poison hands","Bungo Stray Dogs",450],
  ["What is the name of Nakajima Atsushi in Bungo Stray Dogs?","A weretiger who joins the Armed Detective Agency","A government agent","A Port Mafia member","An orphan with no power","Bungo Stray Dogs",300],
  ["What is the main villain organization in Bungo Stray Dogs?","Port Mafia (and later the Decay of Angels)","The Guild","The Hunting Dogs","The Order of the Clock Tower","Bungo Stray Dogs",400],
  ["What is the main character's power in The Rising of the Shield Hero?","Shield abilities that grow stronger over time","Offensive magic","Speed-based skills","Healing abilities","Shield Hero",300],
  ["What is Naofumi falsely accused of in Shield Hero?","Stealing from and assaulting Myne (Malty)","Murder","Espionage","Cheating in the wave battles","Shield Hero",350],
  ["What is the setting of Talentless Nana?","A school for students with supernatural abilities called the Talented","A government lab","A normal high school","An underground facility","Talentless Nana",300],
  ["What is the twist in Talentless Nana episode 2?","Nana is actually a spy sent to kill the Talented students","The school is a trap","Everyone is already dead","The principal is evil","Talentless Nana",450],
  ["What is the Classroom of the Elite about?","A prestigious school where class rank determines your worth and future","A magic academy","A sports school","A delinquent reform school","Classroom of the Elite",300],
  ["Who is Ayanokoji Kiyotaka in Classroom of the Elite?","A student hiding an extraordinary intellect and strategic mind","A former soldier","A student with photographic memory","An AI","Classroom of the Elite",400],
  ["What is Saiki K about?","A high school student with every psychic power who just wants a peaceful life","A psychic superhero story","A supernatural school drama","A comedy about a mage","Saiki K",250],
  ["What is the main gimmick of Mob Psycho 100?","Mob suppresses his powers and emotions causing dramatic releases at 100%","He is an uncontrollable psychic","He fights other psychics in tournaments","He is secretly evil","Mob Psycho",350],
  ["What is the main difference between Log Horizon and SAO?","Log Horizon players cannot die and focus on building society in the game world","They are exactly the same","SAO players can die; Log Horizon cannot","Log Horizon has no combat","Log Horizon",400],
  ["What is Gintoki's signature weapon in Gintama?","A wooden sword (bokuto) that he uses despite being a former elite swordsman","A real katana","A pistol","A spear","Gintama",400],
  ["Who is Orihara Izaya in Durarara?","An information broker who loves humans and manipulates events for entertainment","A gang leader","A detective","A police informant","Durarara",350],
  ["What is Shizuo Heiwajima's signature look in Durarara?","Bartender uniform","School uniform","Military jacket","Suit","Durarara",400],
  ["What is Sword Art Online: Progressive about?","A floor-by-floor retelling of Aincrad with more detail on Asuna's role","An alternate SAO universe","The Alicization arc","The GGO arc","SAO",400],
  ["What is Hinata Shoyo's main strength in Haikyuu?","His incredible jumping height and speed despite his small stature","His serving accuracy","His blocking technique","His setting precision","Haikyuu",300],
  ["What is Free! about specifically?","High school swimmers with different styles reuniting to form a club","Professional swimmers","Olympic training","A water polo team","Free",250],
  ["What is Monthly Girls' Nozaki-kun about?","A male student who secretly creates shojo manga using his classmates","A manga artist and his assistants","A romance between manga rivals","An anime production story","Nozaki-kun",300],
  ["What is the Promised Neverland's twist?","The children discover their orphanage is a farm that sells them to demons","The orphanage is a simulation","The children are already demons","The caretaker is secretly their mother","Promised Neverland",300],
  ["What is the main character of The Promised Neverland?","Emma - an optimistic girl determined to escape with all the children","Norman - a calculating genius","Ray - a cynical realist","Phil - the youngest leader","Promised Neverland",300],
  ["What makes Emma different from Norman and Ray in Promised Neverland?","She refuses to leave any child behind even if it complicates the plan","She is smarter than both","She discovered the truth first","She has a special gift","Promised Neverland",400],
  ["What is Black Rock Shooter in the OVA?","A warrior in another dimension who fights against fate","A school girl with a gun","A supernatural detective","An alien hybrid","Black Rock Shooter",350],
  ["What is Given about?","A rock band forming around a quiet guitarist meeting a boy who can sing","A classical music drama","A piano competition story","A music school drama","Given",300],
  ["What is Fruits Basket 2019 notable for?","Being a faithful complete adaptation of the manga including the true ending","Having better animation than the original","Adding new story arcs","Being directed by a famous director","Fruits Basket",400],
  ["What is the final form of the Sohma curse in Fruits Basket?","The God of the Zodiac (Akito) releases all cursed members as the curse breaks","It intensifies for the main Sohmas","Only Kyo's curse breaks","It transfers to Tohru","Fruits Basket",500],
  ["What is Yuri Katsuki's biggest character challenge in Yuri on Ice?","Overcoming anxiety and self-doubt to compete at the highest level","Beating Victor","Learning a new jump","Qualifying for the Grand Prix","Yuri on Ice",350],
  ["What is the tone of Dr. Stone?","Optimistic and educational - rebuilding civilization with science and friendship","Dark and post-apocalyptic","Action-heavy with fighting","A slow slice-of-life","Dr. Stone",300],
  ["What is the de-petrification fluid in Dr. Stone?","Nitric acid mixed with cave bat droppings in water","Sulfuric acid","A magical compound","An ancient medicine","Dr. Stone",400],
  ["What is the first major invention Senku creates in Dr. Stone?","Nital (de-petrification fluid) to free Taiju and others","A radio","Gunpowder","A steam engine","Dr. Stone",400],
  ["What is Rimuru's inner advisor skill called in Slime Isekai?","Great Sage (later Raphael)","Oracle","Wisdom King","Advisor Spirit","Slime Isekai",350],
  ["Who is Milim Nava in Slime Isekai?","A Demon Lord who is one of the oldest and most powerful beings alive","Rimuru's first ally","A dragon transformed","A human reincarnate","Slime Isekai",400],
  ["What is the tone of Overlord?","The main character is OP and evil-aligned, building an empire as a villain protagonist","A hero saves the world","A classic isekai with a weak-to-strong arc","A political intrigue story","Overlord",350],
  ["What is Ainz's main concern in Overlord?","Keeping up the facade of being all-knowing and powerful so his guardians don't lose faith","World domination","Finding a way home","Gathering treasures","Overlord",450],
  ["What is Demiurge believed to be by the Nazarick guardians?","A genius strategist second only to Ainz","The most powerful warrior","An oracle","Ainz's right hand","Overlord",450],
  ["What is the name of Pandora's Actor in Overlord?","Pandora's Actor - an Area Guardian created in Ainz's image as an NPC","Ainz's personal guard","A Pleiades Battle Maid","A Floor Guardian","Overlord",450],
  ["What is the main appeal of KonoSuba?","Comedy and parody of isekai tropes with useless party members","Serious world-building","Intense action sequences","A deep romance story","KonoSuba",300],
  ["What is Megumin's background in KonoSuba?","She is from the Crimson Demon clan known for explosion magic","She is a noble's daughter","She is a self-trained mage","She is from another world","KonoSuba",400],
  ["What is Aqua's actual divine power in KonoSuba?","She is a true goddess who can perform divine miracles but is useless in practice","She has no actual powers","She can only purify water","She can only bless others","KonoSuba",400],
  ["What is the main theme of Vinland Saga?","The pursuit of a land of peace and rejecting violence as a solution","Viking glory and adventure","War and conquest","Revenge against the world","Vinland Saga",400],
  ["What is Askeladd's backstory in Vinland Saga?","He is half Welsh and hates Vikings but uses them to survive","He is a pure Viking warrior","He seeks Vinland for himself","He is a Frankish mercenary","Vinland Saga",450],
  ["What is Thorfinn's character arc in Vinland Saga?","From revenge-seeking to peaceful warrior finding meaning beyond violence","From weak to strong","From peasant to king","From soldier to leader","Vinland Saga",400],
  ["What is Canute's transformation in Vinland Saga?","From timid prince to ruthless king willing to sacrifice anything for his vision","From warrior to scholar","From villain to hero","From enemy to ally","Vinland Saga",450],
]

out_path = r'C:\Users\luisc\Desktop\Project\PochiPochi\server\anime_raw.json'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f'Written {len(questions)} questions to anime_raw.json')
